[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_URL = "https://seu-backend-api.exemplo.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 